### ISSUE TITLE
"TypeError: Cannot read property 'match' of null"

### ISSUE THREAD

**Issue by PaulHasAProblem** [IBM/email-support-classifier#4]
Hey I was trying to rebuild the stuff from this video here:
https://www.youtube.com/watch?v=-kJmUZFIRMg

Unfortunatly I got the error message when I deployed the flow in Node-red. I rebuild everything the exept same way. 
Does somebody has an idea where the problem might be located?

Best regards and thanks,
Paul

(Let me know if you need if and what information you might need additionaly, I am new to this form. My bad!)

**Comment by muralidharchavan** [comment]
Hi. Seems there is some issue with connecting to cloudant using the cloudant node configured as external cloudant database. While I take this issue up with appropriate team, there is a workaround.
You may use the cloudant database that get's created as part of node red service creation. For this, double click on cloudant nodes in your node red flow and under service dropdown, select the cloudant database that was created as part of node red instead of "external cloudant or couch service". Deploy the flow and it should work fine now.
